version: "3.4"

services:
    patientservice:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          #- "32768:443"
          - "8080:80"
        depends_on:
          - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "P@ssword1"
            ACCEPT_EULA: "Y"